<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($product->name); ?>' by
    '<?php echo $this->escapeHtml($product->description); ?>'?
</p>
<?php
$url = $this->url('product', array('action' => 'delete','id' => $this->id));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $product->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>