<?php
$title = 'My Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('product', array('action'=>'add'));?>"><?php echo $this->translate('Add new Product'); ?></a>
</p>

<table class="table">
    <tr>
        <th><?php echo $this->translate('code'); ?></th>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Description'); ?></th>
        <th><?php echo $this->translate('Status'); ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($products as $product) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($product->code);?></td>
            <td><?php echo $this->escapeHtml($product->name);?></td>
            <td><?php echo $this->escapeHtml($product->description);?></td>
            <td><?php echo $this->escapeHtml($product->status);?></td>
            <td>
                <a href="<?php echo $this->url('product',
                    array('action'=>'edit', 'id' => $product->id));?>">Edit</a>
                <a href="<?php echo $this->url('product',
                    array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>